"""Generate PyBind11 bindings for SGEMM kernels.

This script reads kernel configurations from kernels.py and generates
sgemm_bindings.cu with all necessary PyBind11 bindings.
"""

from kernels import KERNELS


def generate_template_params(params):
    """Generate template parameter string."""
    if not params:
        return ""
    return f"<{', '.join(map(str, params))}>"


def generate_launch_sgemm_function():
    """Generate the launch_sgemm template function with all kernel versions."""
    lines = [
        "#include <torch/extension.h>",
        "",
        '#include "sgemm.cuh"',
        "",
        "template <int VER>",
        "torch::Tensor launch_sgemm(torch::Tensor const input, torch::Tensor const other,",
        "                           torch::Tensor const output) {",
        "  int const M = input.size(0);",
        "  int const K = other.size(0);",
        "  int const N = other.size(1);",
        "",
    ]

    # Generate if-else chain for each kernel version
    for idx, kernel in enumerate(KERNELS):
        template_params = generate_template_params(kernel["template_params"])

        if idx == 0:
            lines.append(f"  if constexpr (VER == {idx}) {{")
        else:
            lines.append(f"  }} else if constexpr (VER == {idx}) {{")

        lines.append(f"    {kernel['launch_func']}{template_params}(output.data_ptr<float>(), input.data_ptr<float>(),")
        lines.append("                       other.data_ptr<float>(), M, N, K);")

    lines.extend(
        [
            "  } else {",
            '    TORCH_CHECK(false, "Unsupported version");',
            "  }",
            "",
            "  return output;",
            "}",
            "",
        ]
    )

    return "\n".join(lines)


def generate_pybind_module():
    """Generate PYBIND11_MODULE with all kernel bindings."""
    lines = [
        "PYBIND11_MODULE(TORCH_EXTENSION_NAME, m) {",
    ]

    for idx, kernel in enumerate(KERNELS):
        python_name = kernel["python_name"]
        lines.append(f'  m.def("{python_name}", launch_sgemm<{idx}>, py::arg("input"), py::arg("other"),')
        lines.append('        py::arg("out"));')

    lines.append("}")

    return "\n".join(lines)


def main():
    """Generate sgemm_bindings.cu file."""
    output_file = "sgemm_bindings.cu"

    with open(output_file, "w") as f:
        f.write("// Auto-generated file - do not edit manually\n")
        f.write("// Generated by generate_bindings.py from kernels.py\n")
        f.write("\n")
        f.write(generate_launch_sgemm_function())
        f.write("\n")
        f.write(generate_pybind_module())
        f.write("\n")

    print(f"Generated {output_file} with {len(KERNELS)} kernel bindings")


if __name__ == "__main__":
    main()
